<?php
require_once '../config/config.php';
cekRole('owner');
$page_title = 'Backup Database';

// Export SQL
if (isset($_GET['export'])&&$_GET['export']==='1') {
    $tables=[];
    $r=$conn->query("SHOW TABLES");
    while($row=$r->fetch_array()) $tables[]=$row[0];

    $sql="-- ================================================\n";
    $sql.="-- GYA COSMETICS DATABASE BACKUP\n";
    $sql.="-- Tanggal: ".date('Y-m-d H:i:s')."\n";
    $sql.="-- Generated by: ".htmlspecialchars($_SESSION['nama'])."\n";
    $sql.="-- ================================================\n\n";
    $sql.="SET FOREIGN_KEY_CHECKS=0;\n\n";

    foreach($tables as $table){
        $sql.="-- Tabel: $table\n";
        $sql.="DROP TABLE IF EXISTS `$table`;\n";
        $cr=$conn->query("SHOW CREATE TABLE `$table`")->fetch_assoc();
        $sql.=$cr['Create Table'].";\n\n";
        $rows=$conn->query("SELECT * FROM `$table`");
        if($rows&&$rows->num_rows>0){
            $sql.="INSERT INTO `$table` VALUES\n";
            $ra=[];
            while($row=$rows->fetch_row()){
                $vals=array_map(function($v)use($conn){return $v===null?'NULL':"'".$conn->real_escape_string($v)."'";}, $row);
                $ra[]="(".implode(",",$vals).")";
            }
            $sql.=implode(",\n",$ra).";\n\n";
        }
    }
    $sql.="SET FOREIGN_KEY_CHECKS=1;\n";

    $filename='gya_cosmetics_backup_'.date('Ymd_His').'.sql';
    simpanLog($_SESSION['user_id'],'backup_database',"Export: $filename");
    header('Content-Type: application/octet-stream');
    header("Content-Disposition: attachment; filename=$filename");
    header('Content-Length: '.strlen($sql));
    echo $sql;
    exit();
}

// Info tabel
$tables_info=[];
$tr=$conn->query("SHOW TABLES");
while($t=$tr->fetch_array()){
    $tn=$t[0];
    $cnt=(int)$conn->query("SELECT COUNT(*) as n FROM `$tn`")->fetch_assoc()['n'];
    $sz=$conn->query("SELECT ROUND((data_length+index_length)/1024,2) as sz FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='$tn'")->fetch_assoc()['sz']??0;
    $tables_info[]=['name'=>$tn,'rows'=>$cnt,'size'=>$sz];
}
$total_rows=array_sum(array_column($tables_info,'rows'));
$total_size=round(array_sum(array_column($tables_info,'size')),2);

// Log backup terakhir
$last_backup=$conn->query("SELECT created_at FROM activity_log WHERE aktivitas='backup_database' ORDER BY created_at DESC LIMIT 1")->fetch_assoc();

require_once '../views/owner_header.php';
?>

<div style="margin-bottom:28px;">
  <h2 style="font-family:'Cormorant Garamond',serif;font-size:1.6rem;font-weight:600;color:#1a0a14;margin-bottom:4px;">Backup Database</h2>
  <p style="font-size:.84rem;color:#b08fa0;">Export & amankan seluruh data GYA Cosmetics</p>
</div>

<div class="row g-3 mb-4">
  <!-- EXPORT CARD -->
  <div class="col-lg-5">
    <div class="stat-card" style="border-top:3px solid rgba(16,185,129,.5);text-align:center;padding:44px 32px;">
      <!-- Animated icon -->
      <div style="width:80px;height:80px;border-radius:22px;background:rgba(16,185,129,.12);display:flex;align-items:center;justify-content:center;font-size:2.2rem;color:#10b981;margin:0 auto 20px;border:1px solid rgba(16,185,129,.2);">
        <i class="bi bi-cloud-download" style="animation:pulse 2s ease-in-out infinite;"></i>
      </div>
      <div style="font-family:'Cormorant Garamond',serif;font-size:1.5rem;font-weight:600;color:#1a0a14;margin-bottom:8px;">Export Database</div>
      <p style="font-size:.83rem;color:#b08fa0;margin-bottom:8px;line-height:1.6;">Download seluruh data GYA Cosmetics dalam format <code style="background:rgba(244,63,136,.08);color:#c2185b;padding:2px 6px;border-radius:5px;">.sql</code></p>
      <?php if($last_backup): ?>
      <div style="font-size:.75rem;color:#b08fa0;margin-bottom:20px;">
        <i class="bi bi-clock"></i> Backup terakhir: <?= date('d/m/Y H:i',strtotime($last_backup['created_at'])) ?>
      </div>
      <?php else: ?>
      <div style="font-size:.75rem;color:#b08fa0;margin-bottom:20px;"><i class="bi bi-exclamation-circle"></i> Belum pernah backup!</div>
      <?php endif; ?>
      <a href="?export=1" class="btn-gya btn-primary-gya" style="display:inline-flex;justify-content:center;padding:13px 28px;font-size:.9rem;">
        <i class="bi bi-download"></i> Download Backup SQL
      </a>
      <div style="margin-top:14px;font-size:.73rem;color:#b08fa0;"><i class="bi bi-info-circle"></i> File otomatis terunduh ke komputer kamu</div>
    </div>
  </div>

  <!-- DATABASE INFO -->
  <div class="col-lg-7">
    <div class="content-card" style="height:100%;">
      <div class="content-card-header">
        <div class="content-card-title"><i class="bi bi-database" style="color:#7c3aed;"></i> Info Database</div>
        <div style="display:flex;gap:12px;font-size:.78rem;color:#b08fa0;">
          <span><i class="bi bi-table"></i> <?= count($tables_info) ?> tabel</span>
          <span><i class="bi bi-hdd"></i> <?= $total_size ?> KB</span>
          <span><i class="bi bi-list-ol"></i> <?= number_format($total_rows) ?> baris</span>
        </div>
      </div>
      <div style="max-height:320px;overflow-y:auto;">
        <table class="table-gya">
          <thead><tr><th>Nama Tabel</th><th>Jumlah Data</th><th>Ukuran</th><th>Status</th></tr></thead>
          <tbody>
            <?php foreach($tables_info as $t): ?>
            <tr>
              <td><code style="background:rgba(139,92,246,.08);color:#7c3aed;padding:3px 9px;border-radius:7px;font-size:.79rem;"><?= htmlspecialchars($t['name']) ?></code></td>
              <td><span class="badge-gya badge-purple"><?= number_format($t['rows']) ?> baris</span></td>
              <td style="font-size:.83rem;color:#7c3f5e;"><?= $t['size'] ?> KB</td>
              <td><span class="badge-gya badge-success"><i class="bi bi-check-circle-fill" style="font-size:.55rem;"></i> OK</span></td>
            </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- TIPS BACKUP -->
<div class="content-card">
  <div class="content-card-header">
    <div class="content-card-title"><i class="bi bi-lightbulb" style="color:#f59e0b;"></i> Panduan Backup & Restore</div>
  </div>
  <div style="padding:20px 24px;">
    <div class="row g-3">
      <?php
      $tips=[
        ['bi-calendar-check','#10b981','Backup Rutin','Lakukan backup minimal seminggu sekali. Saat ramai transaksi, backup harian lebih aman.'],
        ['bi-folder2-open','#3b82f6','Simpan di Beberapa Tempat','Upload ke Google Drive, kirim ke email, atau simpan di flashdisk. Jangan hanya di satu tempat.'],
        ['bi-shield-check','#f59e0b','Sebelum Perubahan Besar','Selalu backup sebelum update sistem, hapus data massal, atau ubah struktur database.'],
        ['bi-arrow-repeat','#7c3aed','Cara Restore','Buka phpMyAdmin → pilih database gya_cosmetics → klik Import → pilih file .sql backup → Go.'],
        ['bi-bug','#ef4444','Jika Data Rusak','Jangan panik. Hapus database lama, buat baru dengan nama sama, lalu import file backup terakhir.'],
        ['bi-clock-history','#f43f88','Cek Riwayat Backup','Lihat Activity Log untuk memastikan backup rutin berjalan dan dilakukan oleh user yang benar.'],
      ];
      foreach($tips as [$ic,$cl,$title,$desc]): ?>
      <div class="col-md-6">
        <div style="display:flex;gap:12px;padding:15px;background:rgba(244,63,136,.03);border-radius:14px;border:1px solid rgba(244,63,136,.07);">
          <div style="width:42px;height:42px;border-radius:12px;background:<?=$cl?>18;display:flex;align-items:center;justify-content:center;color:<?=$cl?>;font-size:1.15rem;flex-shrink:0;">
            <i class="bi <?=$ic?>"></i>
          </div>
          <div>
            <div style="font-weight:700;font-size:.86rem;color:#1a0a14;margin-bottom:4px;"><?=$title?></div>
            <div style="font-size:.78rem;color:#9d7a8a;line-height:1.55;"><?=$desc?></div>
          </div>
        </div>
      </div>
      <?php endforeach; ?>
    </div>
  </div>
</div>

<style>
@keyframes pulse{0%,100%{transform:scale(1);}50%{transform:scale(1.08);}}
</style>
<?php require_once '../views/owner_footer.php'; ?>